---
kind: pipeline
type: docker
name: amd64

steps:
  - name: Build
    image: plugins/docker
    settings:
      mirror:
        from_secret: DOCKER_MIRROR
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
      repo: aricodes/tor
      tags:
        - amd64

---
kind: pipeline
type: docker
name: i386

steps:
  - name: Binfmt
    image: tonistiigi/binfmt
    privileged: true
    entrypoint:
      - /usr/bin/binfmt
      - --install
      - all

  - name: Build
    image: thegeeklab/drone-docker-buildx
    privileged: true
    settings:
      experimental: true
      platforms:
        - linux/386
      mirror:
        from_secret: DOCKER_MIRROR
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
      repo: aricodes/tor
      tags:
        - i386

---
kind: pipeline
type: docker
name: arm64

platform:
  os: linux
  arch: arm64

steps:
  - name: Build
    image: plugins/docker
    settings:
      mirror:
        from_secret: DOCKER_MIRROR
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
      repo: aricodes/tor
      tags:
        - arm64

---
kind: pipeline
type: docker
name: arm32

platform:
  os: linux
  arch: arm64

steps:
  - name: Binfmt
    image: tonistiigi/binfmt
    privileged: true
    entrypoint:
      - /usr/bin/binfmt
      - --install
      - all

  - name: Build
    image: thegeeklab/drone-docker-buildx
    privileged: true
    settings:
      experimental: true
      platforms:
        - linux/arm
      mirror:
        from_secret: DOCKER_MIRROR
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
      repo: aricodes/tor
      tags:
        - arm

---
kind: pipeline
type: docker
name: Publish

depends_on:
  - amd64
  - i386
  - arm64
  - arm32

platform:
  os: linux
  arch: arm64

steps:
  - name: Tag manifest
    image: docker:dind
    privileged: true
    environment:
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
    commands:
      - docker login -u $username -p $password
      - docker manifest create aricodes/tor:latest --amend aricodes/tor:amd64 --amend aricodes/tor:i386 --amend aricodes/tor:arm64 --amend aricodes/tor:arm
      - docker manifest push aricodes/tor:latest
