kind: pipeline
type: docker
name: Build multiarch image

steps:
  - name: Binfmt
    image: tonistiigi/binfmt
    privileged: true
    entrypoint:
      - /usr/bin/binfmt
      - --install
      - all

  - name: Build
    image: thegeeklab/drone-docker-buildx
    privileged: true
    settings:
      experimental: true
      platforms:
        - linux/amd64
        - linux/386
        - linux/arm64
        - linux/arm
      mirror:
        from_secret: DOCKER_MIRROR
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
      repo: aricodes/tor
      tags:
        - latest
